In [1]:
from datetime import datetime
import lxml
from lxml import html
import requests
import numpy as np
import pandas as pd
import yfinance as yf
import io

In [2]:
tickers = ['RACB','TUYA','JWEL','OLO','SNCY','HAYW','JOAN','MITC'
,'RXDX'
,'CPNG'
,'FHS'
,'RBLX'
,'VAQC'
,'SVFB'
,'SVFC'
,'TWOA'
,'LHAA'
,'INNV'
,'KVSA'
,'OSCR'
,'ARYD'
,'SCR'
,'BCTX'
,'ABGI'
,'VRPX'
,'DBTX'
,'LGVN'
,'NEXI'
,'TLIS'
,'UGRO'
,'APR'
,'BVS'
,'BMBL'
,'LDI'
,'SGFY'
,'BPTS'
,'VLON'
,'DSP'
,'ADAG'
,'RAAS'
,'SDH'
,'BAOS'
,'ANGN'
,'BOLT'
,'CNEY'
,'EVAX'
,'FWAA'
,'IMCR'
,'LHDX'
,'PHVS'
,'TERN'
,'VOR'
,'ATC'
,'LABP'
,'SANA'
,'SNSE'
,'ONTF'
,'TIXT'
,'HMPT'
,'TRIN'
,'AGFY'
,'OCDX'
,'XM'
,'VINP'
,'ZIM'
,'HCAQ'
,'SHLS'
,'TIRX'
,'BTNB'
,'EZGO'
,'HUDI'
,'MNTK'
,'PAX'
,'RLX'
,'DFH'
,'MYTE'
,'DRVN'
,'PLTK'
,'TBA.U'
,'WOOF'
,'POSH'
,'AFRM'
,'MSGM'
,'KUKE'
,'QLI'
,'CGEM'
,'GRCL'
,'OMEG'
,'MRM'
,'IKT'
,'MASS'
,'MDWT'
,'VIRI'
,'BCAB'
,'WISH'
,'UPST'
,'OCG'
,'WNW'
,'FDMT'
,'ABCL'
,'CERT'
,'VVOS'
,'ABNB'
,'HYFM'
,'AI'
,'DAS'
,'PUBM'
,'YQ'
,'SEE'
,'SGTX'
,'SBTX'
,'KNTE'
,'HFEN'
,'OZON'
,'VMAR'
,'MRVI'
,'SHC'
,'NGMS'
,'OLMA'
,'YSG'
,'AVIR'
,'LU'
,'SQZ'
,'ALGM'
,'GLTO'
,'LESL'
,'BDSX'
,'GATO'
,'MAX'
,'ROOT'
,'FHTX'
,'ABCM'
,'BLSA'
,'GHLD'
,'MCFE'
,'MSP'
,'YGMZ'
,'HLXA'
,'ALGS'
,'EAR'
,'KRBP'
,'PRAX'
,'TARS'
,'ARRY'
,'MNSO'
,'CDA'
,'IH'
,'KRON'
,'SPRB'
,'AZYO'
,'FUBO'
,'SQFT'
,'ASO'
,'CCCC'
,'IMNM'
,'ONCR'
,'LXEH'
,'AVO'
,'LUNG'
,'THR'
,'BQ'
,'CD'
,'PLTR'
,'YALA'
,'ORPH'
,'AMST'
,'GRAY'
,'GLSI'
,'PMVP'
,'PRLD'
,'VIAO'
,'TSHA'
,'BSY'
,'CRSR'
,'GDRX'
,'LSF'
,'ATH'
,'CM'
,'U'
,'VTRU'
,'AMWL'
,'BNL'
,'PTVE'
,'SUMO'
,'FROG'
,'SNOW'
,'AUVI'
,'HCDI'
,'XPEV'
,'KYMR'
,'NNOX'
,'HRMY'
,'INBX'
,'CVAC'
,'DCT'
,'NTST'
,'FSDC'
,'ARYA'
,'CMPI'
,'FRLN'
,'IBEX'
,'AFIB'
,'OSH'
,'RKT'
,'BIGC'
,'RXT'
,'HSAQ'
,'GOED'
,'FTHM'
,'VSTA'
,'VITL'
,'ALVR'
,'LI'
,'VER'
,'ANNX'
,'INZY'
,'ITOS'
,'NRIX'
,'MEG'
,'EDTK'
,'JAMF'
,'ALXO'
,'BLI'
,'PAND'
,'RLAY'
,'TIG'
,'GOCO'
,'NCNO'
,'NKTX'
,'PSTX'
,'QH'
,'BLC'
,'TXAC'
,'ACCD'
,'LMND'
,'DNB'
,'API'
,'AKUS'
,'ACI'
,'EBON'
,'FUSN'
,'PYPD'
,'FMTX'
,'GTH'
,'PROG'
,'RPTX'
,'RPRX'
,'RNA'
,'AZEK'
,'BNR'
,'GBIO'
,'PCVX'
,'LTRN'
,'UCL'
,'HECCU'
,'VRM'
,'AMTI'
,'DADA'
,'LEGN'
,'FOUR'
,'ZI'
,'PLRX'
,'WMG'
,'NARI'
,'SLQT'
,'ADCT'
,'AYLA'
,'CLEU'
,'KC'
,'LYR'
,'ORIC'
,'KROS'
,'ZNTL'
,'WIMI'
,'IMRA'
,'GFL'
,'PASG'
,'ZCMD'
,'GRIL'
,'RVMD'
,'HUIZ'
,'NREF'
,'ONEW'
,'BEAM'
,'CSPR'
,'PPD'
,'SDGR'
,'ONEM'
,'ARQT'
,'REYN'
,'ANPC'
,'BDTX'
,'ANVS'
,'IMAB'
,'LIZI'
,'DNK'
,'VEL'
,'MKD'
,'INDO'
,'MNPR'
,'OCFT'
,'SPT'
,'BILL'
,'EH'
,'XP'
,'LMPX'
,'PINE'
,'CAN'
,'SITM'
,'YAYO'
,'ETNB'
,'KRKR'
,'CNSP'
,'MOHO'
,'TELA'
,'CNTG'
,'GRTX'
,'SI'
,'QK'
,'DUO'
,'OYST'
,'RAPT'
,'AIH'
,'CABA'
,'HAPP'
,'PHAT'
,'PGNY'
,'TFFP'
,'DAO'
,'BRP'
,'BRBR'
,'HBT'
,'VIR'
,'BNTX'
,'APRE'
,'FREQ'
,'VIE'
,'OPRT'
,'PTON'
,'DDOG'
,'XGN'
,'PING'
,'NVST'
,'IGMS'
,'NET'
,'STSA'
,'SWTX'
,'TXG'
,'SDC'
,'JFU'
,'CFB'
,'INMD'
,'HKIB'
,'DT'
,'KRUS'
,'SNDL'
,'BHAT'
,'WSG'
,'CSTL'
,'HCAT'
,'LVGO'
,'PROS'
,'NOVA'
,'AFYA'
,'MDLA'
,'AMK'
,'FULC'
,'MIRM'
,'ORCC'
,'PHR'
,'DOYU'
,'KRTX'
,'REAL'
,'ADPT'
,'BBIO'
,'CHNG'
,'MORF'
,'BSTZ'
,'CMBM'
,'AKRO'
,'BCE'
,'GO'
,'PSNL'
,'PRVL'
,'STOK'
,'CHWY'
,'FVRR'
,'CRWD'
,'MWK'
,'GSX'
,'BCYC'
,'IDYA'
,'RTLR'
,'AVTR'
,'FSLY'
,'PSTL'
,'APLT'
,'JFIN'
,'SONM'
,'UBER'
,'AXLA'
,'CRTX'
,'HHR'
,'MEC'
,'MIST'
,'NXTC'
,'SPFI'
,'PSN'
,'TRVI'
,'RRBI'
,'SCPL'
,'BYND'
,'SY'
,'TMDX'
,'MNRL'
,'GNLN'
,'HOOK'
,'PINS'
,'ZM'
,'TPTX'
,'JMIA'
,'PD'
,'TUFN'
,'GHSI'
,'SILK'
,'TW'
,'RUHN'
,'PBTS'
,'LYFT'
,'LEVI'
,'TIGR'
,'FHL'
,'SWAV'
,'KLDO'
,'SLGG'
,'HOTH'
,'AVDR'
,'TCRR'
,'HARP'
,'ALEC'
,'NFE'
,'MTC'
,'QFIN'
,'TME'
,'MRNA'
,'THOR'
,'MOGU'
,'MDRR'
,'TC'
,'BCSF'
,'WEI'
,'VAPO'
,'ETON'
,'CNF'
,'AXNX'
,'ORTX'
,'TWST'
,'GMDA'
,'PT'
,'YETI'
,'LOGC'
,'NIU'
,'SWI'
,'OSMT'
,'PHAS'
,'MSC'
,'SIBN'
,'PLAN'
,'EQ'
,'ALLO'
,'LTHM'
,'ESTC'
,'GH'
,'KOD'
,'UPWK'
,'CTK'
,'ARVN'
,'LAIX'
,'RMED'
,'UROV'
,'ARCE'
,'CBNK'
,'ETTX'
,'SVMK'
,'VIOT'
,'FTCH'
,'STRO'
,'YMAB'
,'BSVN'
,'ELAN'
,'EB'
,'XYF'
,'FVCB'
,'PRNB'
,'QTT'
,'YI'
,'NIO'
,'ARDS'
,'MESA'
,'VCNX'
,'ARLO'
,'CWK'
,'SONO'
,'BRY'
,'DAVA'
,'OPRA'
,'JG'
,'CANG'
,'FOCS'
,'LQDA'
,'PDD'
,'TENB'
,'AQST'
,'BE'
,'REPL'
,'ALLK'
,'CNST'
,'ESTA'
,'MYFW'
,'TLRY'
,'CCB'
,'CRNX'
,'RUBY'
,'DOMO']

In [3]:
tickers = [yf.Ticker(ticker) for ticker in tickers]

In [4]:
dfs = [] # list for each ticker's dataframe
for ticker in tickers:
    # get each financial statement
    pnl = ticker.financials
    bs = ticker.balancesheet
    cf = ticker.cashflow

    # concatenate into one dataframe
    fs = pd.concat([pnl, bs, cf])

    # make dataframe format nicer
    # Swap dates and columns
    data = fs.T
    # reset index (date) into a column
    data = data.reset_index()
    # Rename old index from '' to Date
    data.columns = ['Date', *data.columns[1:]]
    # Add ticker to dataframe
    data['Ticker'] = ticker.ticker
    dfs.append(data)
data.iloc[:,:3]# for display purposes

        Date Research Development Effect Of Accounting Charges
0 2021-01-31           66474000.0                         None
1 2020-01-31           69224000.0                         None
2 2019-01-31           75740000.0                         None
3 2018-01-31           78261000.0                         None

In [5]:
data

,Date,Research Development,Effect Of Accounting Charges,Income Before Tax,Minority Interest,Net Income,Selling General Administrative,Gross Profit,Ebit,Operating Income,...,Repurchase Of Stock,Effect Of Exchange Rate,Total Cash From Operating Activities,Depreciation,Change To Account Receivables,Change To Netincome,Capital Expenditures,Net Borrowings,Other Cashflows From Financing Activities,Ticker
0,2021-01-31,66474000.0,None,-84225000.0,None,-84634000.0,159243000.0,153432000.0,-72729000.0,-72729000.0,...,-1745000.0,488000.0,-15872000.0,1765000.0,-305000.0,42058000.0,-5706000.0,NaN,NaN,DOMO
1,2020-01-31,69224000.0,None,-124902000.0,None,-125656000.0,164808000.0,117465000.0,-115457000.0,-115457000.0,...,-1428000.0,-80000.0,-80219000.0,3217000.0,454000.0,25806000.0,-6466000.0,NaN,NaN,DOMO
2,2019-01-31,75740000.0,None,-153061000.0,None,-154309000.0,161257000.0,92910000.0,-144117000.0,-144117000.0,...,-1428000.0,9000.0,-131367000.0,4887000.0,-12937000.0,20525000.0,-6373000.0,49598000.0,-4140000.0,DOMO
3,2018-01-31,78261000.0,None,-176177000.0,None,-176562000.0,161125000.0,63605000.0,-175817000.0,-175817000.0,...,-121000.0,141000.0,-148657000.0,4931000.0,-13186000.0,9544000.0,-7281000.0,48863000.0,-38000.0,DOMO

In [6]:
parser = pd.io.parsers.ParserBase({'usecols': None})

for df in dfs:
     df.columns = parser._maybe_dedup_names(df.columns)
df = pd.concat(dfs, ignore_index=False)
df = df.set_index(['Ticker','Date'])
df.iloc[:,:5] # for display purposes

                  Research Development Effect Of Accounting Charges  \
Ticker Date
RACB   2021-12-31                 None                         None
       2020-12-31                 None                         None
TUYA   2021-12-31          174289000.0                         None
       2020-12-31           77430000.0                         None
       2019-12-31           52003000.0                         None
...                                ...                          ...
RUBY   2018-12-31           51769000.0                         None
DOMO   2021-01-31           66474000.0                         None
       2020-01-31           69224000.0                         None
       2019-01-31           75740000.0                         None
       2018-01-31           78261000.0                         None

                  Income Before Tax Minority Interest   Net Income
Ticker Date
RACB   2021-12-31         -456005.0              None    -456005.0
       2020-12-31          -18874.0              None     -18874.0
TUYA   2021-12-31      -174934000.0              None -175424000.0
       2020-12-31       -66706000.0              None  -66912000.0
       2019-12-31       -70353000.0              None  -70477000.0
...                             ...               ...          ...
RUBY   2018-12-31       -89195000.0              None  -89195000.0
DOMO   2021-01-31       -84225000.0              None  -84634000.0
       2020-01-31      -124902000.0              None -125656000.0
       2019-01-31      -153061000.0              None -154309000.0
       2018-01-31      -176177000.0              None -176562000.0

[2025 rows x 5 columns]

In [7]:
df.iloc[:,:1000]

                  Research Development Effect Of Accounting Charges  \
Ticker Date
RACB   2021-12-31                 None                         None
       2020-12-31                 None                         None
TUYA   2021-12-31          174289000.0                         None
       2020-12-31           77430000.0                         None
       2019-12-31           52003000.0                         None
...                                ...                          ...
RUBY   2018-12-31           51769000.0                         None
DOMO   2021-01-31           66474000.0                         None
       2020-01-31           69224000.0                         None
       2019-01-31           75740000.0                         None
       2018-01-31           78261000.0                         None

                  Income Before Tax Minority Interest   Net Income  \
Ticker Date
RACB   2021-12-31         -456005.0              None    -456005.0
       2020-12-31          -18874.0              None     -18874.0
TUYA   2021-12-31      -174934000.0              None -175424000.0
       2020-12-31       -66706000.0              None  -66912000.0
       2019-12-31       -70353000.0              None  -70477000.0
...                             ...               ...          ...
RUBY   2018-12-31       -89195000.0              None  -89195000.0
DOMO   2021-01-31       -84225000.0              None  -84634000.0
       2020-01-31      -124902000.0              None -125656000.0
       2019-01-31      -153061000.0              None -154309000.0
       2018-01-31      -176177000.0              None -176562000.0

                  Selling General Administrative Gross Profit         Ebit  \
Ticker Date
RACB   2021-12-31                           None          0.0          0.0
       2020-12-31                           None          0.0          0.0
TUYA   2021-12-31                    146973000.0  127867000.0 -183560000.0
       2020-12-31                     55424000.0   61937000.0  -69846000.0
       2019-12-31                     49213000.0   27786000.0  -73440000.0
...                                          ...          ...          ...
RUBY   2018-12-31                     39894000.0          0.0  -91663000.0
DOMO   2021-01-31                    159243000.0  153432000.0  -72729000.0
       2020-01-31                    164808000.0  117465000.0 -115457000.0
       2019-01-31                    161257000.0   92910000.0 -144117000.0
       2018-01-31                    161125000.0   63605000.0 -175817000.0

                  Operating Income Other Operating Expenses  ...  \
Ticker Date                                                  ...
RACB   2021-12-31             None                     None  ...
       2020-12-31             None                     None  ...
TUYA   2021-12-31     -183560000.0               -9835000.0  ...
       2020-12-31      -69846000.0               -1071000.0  ...
       2019-12-31      -73440000.0                  10000.0  ...
...                            ...                      ...  ...
RUBY   2018-12-31      -91663000.0                     None  ...
DOMO   2021-01-31      -72729000.0                      NaN  ...
       2020-01-31     -115457000.0               -1300000.0  ...
       2019-01-31     -144117000.0               -1300000.0  ...
       2018-01-31     -175817000.0               -1300000.0  ...

                  Change To Inventory Change To Account Receivables  \
Ticker Date
RACB   2021-12-31                 NaN                           NaN
       2020-12-31                 NaN                           NaN
TUYA   2021-12-31         -22121000.0                   -23430000.0
       2020-12-31         -19787000.0                    -7243000.0
       2019-12-31         -11037000.0                    -4010000.0
...                               ...                           ...
RUBY   2018-12-31                 NaN                           NaN
DOMO   2021-01-31                 NaN                     -305000.0
       2020-01-31                 NaN                      454000.0
       2019-01-31                 NaN                   -12937000.0
       2018-01-31                 NaN                   -13186000.0

                  Capital Expenditures Intangible Assets  \
Ticker Date
RACB   2021-12-31                  NaN               NaN
       2020-12-31                  NaN               NaN
TUYA   2021-12-31           -6193000.0               NaN
       2020-12-31           -3201000.0               NaN
       2019-12-31           -2487000.0               NaN
...                                ...               ...
RUBY   2018-12-31          -14952000.0               NaN
DOMO   2021-01-31           -5706000.0         3356000.0
       2020-01-31           -6466000.0         3865000.0
       2019-01-31           -6373000.0         4415000.0
       2018-01-31           -7281000.0         3026000.0

                  Deferred Long Term Asset Charges Dividends Paid  Good Will  \
Ticker Date
RACB   2021-12-31                              NaN            NaN        NaN
       2020-12-31                              NaN            NaN        NaN
TUYA   2021-12-31                              NaN            NaN        NaN
       2020-12-31                              NaN            NaN        NaN
       2019-12-31                              NaN            NaN        NaN
...                                            ...            ...        ...
RUBY   2018-12-31                              NaN            NaN        NaN
DOMO   2021-01-31                              NaN            NaN  9478000.0
       2020-01-31                              NaN            NaN  9478000.0
       2019-01-31                              NaN            NaN  9478000.0
       2018-01-31                              NaN            NaN  9478000.0

                  Long Term Debt Short Long Term Debt Minority Interest.1
Ticker Date
RACB   2021-12-31            NaN                  NaN                 NaN
       2020-12-31            NaN                  NaN                 NaN
TUYA   2021-12-31            NaN                  NaN                 NaN
       2020-12-31            NaN                  NaN                 NaN
       2019-12-31            NaN                  NaN                 NaN
...                          ...                  ...                 ...
RUBY   2018-12-31     24347000.0                  NaN                 NaN
DOMO   2021-01-31     99609000.0                  NaN                 NaN
       2020-01-31    101074000.0                  NaN                 NaN
       2019-01-31     97245000.0                  NaN                 NaN
       2018-01-31     46332000.0                  NaN                 NaN

[2025 rows x 71 columns]

In [8]:
df.to_csv('YF_scrap_data.csv')